# Generated by Django 6.0.5 on 2026-05-11 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Data-driven builder and problem solver', max_length=120)),
                ('full_name', models.CharField(default='Mohtashim Usmani', max_length=120)),
                ('paragraph_one', models.TextField(default='I am Mohtashim Usmani, a Data Scientist and Full-Stack Web Developer based in Pakistan. I sit at the intersection of data and engineering, equally comfortable training ML models and deploying them behind a polished web interface.')),
                ('paragraph_two', models.TextField(default='My work lives in Python and Django on the backend, where I design data pipelines, REST APIs, and intelligent systems. On the data side, I work across the full lifecycle from raw data wrangling with Pandas to building and evaluating production-ready ML models.')),
                ('years_experience', models.PositiveIntegerField(default=3)),
                ('projects_shipped', models.PositiveIntegerField(default=15)),
                ('models_deployed', models.PositiveIntegerField(default=5)),
                ('fun_stat_label', models.CharField(default='Curiosity', help_text='Label for the fun stat card', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_badge', models.CharField(default='Available for work', max_length=80)),
                ('first_name', models.CharField(default='Mohtashim', max_length=80)),
                ('last_name', models.CharField(default='Usmani', max_length=80)),
                ('role_tagline', models.CharField(default='Data Scientist and Full-Stack Dev', help_text='Shown in italic next to last name', max_length=120)),
                ('description', models.TextField(default='I build intelligent web applications and extract meaning from data. Turning complex datasets into clear insights and shipping full-stack products powered by Python, Django, and Machine Learning.')),
                ('cta_primary_label', models.CharField(default='View My Work', max_length=40)),
                ('cta_primary_url', models.CharField(default='#projects', max_length=200)),
                ('cta_secondary_label', models.CharField(default='Get in Touch', max_length=40)),
                ('cta_secondary_url', models.CharField(default='#contact', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one Hero should be active at a time')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='*', help_text='A single emoji or symbol shown as the service icon', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveIntegerField(default=80, help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('Core', 'Core'), ('Data', 'Data and ML'), ('Web', 'Web'), ('DevOps', 'DevOps')], default='Core', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('twitter', 'Twitter / X'), ('other', 'Other')], max_length=20)),
                ('url', models.CharField(help_text='Full URL or mailto: address for email', max_length=200)),
                ('label', models.CharField(blank=True, help_text='Display label (optional, e.g. github.com/yourname)', max_length=80)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Featured', 'Featured'), ('Live', 'Live'), ('Open Source', 'Open Source'), ('In Progress', 'In Progress'), ('Archived', 'Archived')], default='Featured', max_length=20)),
                ('accent_color', models.CharField(default='#4fffb0', help_text='Hex color for the status badge, e.g. #4fffb0', max_length=10)),
                ('github_url', models.URLField(blank=True, default='', help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, default='', help_text='Live demo URL (optional)')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='api.tag')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
